version: '3.9'

services:

  3d-viewer:
    build:
      context: ./app_3d
      dockerfile: Dockerfile
    ports:
      - "8500:80"

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./data/geojson/:/app/data/geojson
    working_dir: /app
    ports:
      - "8400:8400"

  db:
    image: postgis/postgis:${POSTGIS_VERSION}
    restart: always
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
    ports:
      - "${POSTGIS_PORT}:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=${POSTGIS_USER}
      - POSTGRES_PASSWORD=${POSTGIS_PASSWORD}

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    restart: unless-stopped

  qgis-server:
    image: camptocamp/qgis-server:3.44
    ports:
    - 8080:80
    volumes:
    - ./data/qgisserver/projects:/data:ro
    environment:
    - LANG=en_EN.UTF-8
    - QGIS_PROJECT_FILE=/data/sede_orinoquia.qgz
    - QGIS_SERVER_LOG_LEVEL=0  # INFO (log all requests)
    - DEBUG=1                  # display env before spawning QGIS Server
